language: python
python:
  - "3.5"
  - "3.6"

cache: pip
install:
  - pip install -r requirements.txt
  - pip install coveralls
script:
  - python manage.py makemigrations
  - coverage run --source=phishing manage.py test
after_success: coveralls
