language: python
python:
- '3.5'
- '3.6'
addons:
  sauce_connect: true
cache: pip
install:
- pip install -r requirements.txt
- pip install coveralls
script:
- python manage.py makemigrations
- coverage run --source=phishing manage.py test
after_success: coveralls
env:
  global:
  - secure: bKXH+9GAHQEnadcJRKMxyeWVWvplDd8NYxnMy60pD/REZpsg/tb8yGOzQFoeMv9h5xZBtwkEMfPbzJW0/rXOF1Ah28hID198WKq1HOw49mwCJrHO3WXGVZs1dCNH6xCxKaeBPAIvqDi/MiUTVw7TS8HpjOazAhIpKEDhQ8XUc2W0TeZANNIQgbPrG7fp94EairMGEQoitmb7E/txZZ59yW1czTw0CT8F/qIPKJ/HEGy5JgJO1MZXOTeJeDNCCnaTF7i/53tRM3y66DIWFiNCLHJEHtt0MoGNFmh5wW6zg+S7tBrjJtUIfeQwna6r8mi+dhv4ZRwNF8igMViIDH/ilgpjHd58CHypWGP0kNa2YuW+PKt2aXPqKgQ6AtjoVgPQobchOFUOCpwyN0E7rGK0qNXyKBc0ez39x/0qYezC46+SdtYTAfL4Z/rv9phFQmr058SKl/tcxBubR3N2RkAVj5xFGDHAkCunH7mm1BV79Kr9Ladvn5dM8/O+g7gBkTNR17l9uVZe4jTIQ0vRNJMmWolVwo1BbqArJ0RCrJMEYsZghFQS3fh+KwiVXzUJc5I/W2b8GpxOSqcRe2A5kMlKRTp9mCHfjFDLLKBaVGDkQxiNCGDB23nXKZ7JTylx61aXn4hHT+wnFeVS4G5jl2md681RbvZub4Hc65cvjj0if6A=
  - secure: feo2dCGL8S6WUmf7UGUI/3LebEonT8wDrfY1o7WCiamDkXGQOhtcWmtrczvbl6hhle70tnhi9Vh+ll7NAEoWqsgZ6wArHwRdaNLVO9SyewY0PkGdkRR/HAiq5J0pBh8e6nSC0VEdSPucYywh0BomS4DjMWIJwUGd6/KU4AGwih44jg2Djxehw+lThn9nx0e7AlEti3sLjqe7R0oJp6GLokzx9QL2I7fESvY8q387Cd8M5XYKy3bH9UCAriTt15mhBqyuIjmKaXEg0jDIN7qUg4Vpz/SU75n9Uo74YNqVEWruhrs+5opiK+VomzTMm7DpzIjad385hj+mmoAFI3VQRZEz9pzAtaTXabPmjP93Sg015ZjAPQO3oF5I8LtdRn8fNgtrpL/kHkeLClVML7HXTX/vNqxaqNltGqa7k0eLqaV2Ek+cC7l5Xmxuxjj3D5JCj1UPfB8h2FiMpvhIsFL9JE/R+7eLmgHsI07AxT89DdhwcM8MkseZswNOoDNLv3Cvb26dPiVQ2NYxYGuIN1jFswY4Z0V/xkPab6RtQkqpDj87ycPqr9Ict3REKMOSxh3ro3zBFoqGHJWp9EOt7qyxLKXIqOuxe5WWGQzdMtuMInceTPT9voD1EpgugAX+sHp5nKMjlw7Hd6HfNqLKD/sG3VbokDaCHNhEn4C8jqtydl8=
